/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ScientistRole;

import Business.Data.CropDataDirectory;
import Business.Data.CropMethodDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.EndUserOrganization;
import Business.Organization.ResearchOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Mayank
 */
public class ScientistWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ScientistWorkAreaJPanel
     */
    JPanel container;
    UserAccount account;
    ResearchOrganization researchOrganization;
    EcoSystem business;
    Enterprise enterprise;  

    public ScientistWorkAreaJPanel(JPanel container, UserAccount account, ResearchOrganization researchOrganization, Enterprise enterprise,EcoSystem business) {
        initComponents(); //To change body of generated methods, choose Tools | Templates.
        
        this.container = container;
        this.account = account;
        this.researchOrganization = researchOrganization;
        this.researchOrganization = researchOrganization;
        this.business = business;
        this.enterprise=enterprise;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRequestFunding = new javax.swing.JButton();
        AnalyticsButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jLabel1.setText("SCIENTIST WORK AREA");

        btnRequestFunding.setText("Request Funding");
        btnRequestFunding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestFundingActionPerformed(evt);
            }
        });

        AnalyticsButton.setText("Analytics");
        AnalyticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyticsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AnalyticsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRequestFunding, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(88, 88, 88)
                .addComponent(btnRequestFunding, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(AnalyticsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestFundingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestFundingActionPerformed
        // TODO add your handling code here:
        RequestFundingJPanel chkprogram = new RequestFundingJPanel(container,account,researchOrganization,business);
        container.add("RequestFundingJPane", chkprogram);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        
    }//GEN-LAST:event_btnRequestFundingActionPerformed

    private void AnalyticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyticsButtonActionPerformed
        // TODO add your handling code here:
        AnalyticsJPanel ajp = new AnalyticsJPanel(container);
        container.add("AnalyticsJPanel", ajp);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        
    }//GEN-LAST:event_AnalyticsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalyticsButton;
    private javax.swing.JButton btnRequestFunding;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
