/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FarmerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.FarmerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Mayank
 */
public class FarmerDashBoard extends javax.swing.JPanel {

    /**
     * Creates new form FarmerDashBoard
     */
    JPanel userProcessContainer;
    UserAccount account;
    FarmerOrganization farmerOrganization;
    Enterprise enterprise;
    EcoSystem business;
    

    public FarmerDashBoard(JPanel userProcessContainer, UserAccount account, FarmerOrganization farmerOrganization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.farmerOrganization = farmerOrganization;
        this.enterprise = enterprise;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSellCrop = new javax.swing.JButton();
        btnAnsCummQues = new javax.swing.JButton();

        btnSellCrop.setText("Sell My Crop");
        btnSellCrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellCropActionPerformed(evt);
            }
        });

        btnAnsCummQues.setText("Answer Community Question");
        btnAnsCummQues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnsCummQuesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAnsCummQues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSellCrop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnSellCrop)
                .addGap(42, 42, 42)
                .addComponent(btnAnsCummQues)
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSellCropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellCropActionPerformed
        // TODO add your handling code here:
        SellMyCrop panel = new SellMyCrop(userProcessContainer,  account,  farmerOrganization,  enterprise, business);
        userProcessContainer.add("SellMyCrop", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSellCropActionPerformed

    private void btnAnsCummQuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnsCummQuesActionPerformed
        // TODO add your handling code here:
        FarmerWorkAreaJPanel panel = new FarmerWorkAreaJPanel(userProcessContainer,  account,  farmerOrganization,  enterprise, business);
        userProcessContainer.add("FarmerWorkAreaJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAnsCummQuesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnsCummQues;
    private javax.swing.JButton btnSellCrop;
    // End of variables declaration//GEN-END:variables
}
